apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoroot
  template:
    metadata:
      labels:
        app: autoroot
    spec:
      containers:

        - name: backend
          image: gcr.io/YOUR_PROJECT/backend:latest
          ports:
            - containerPort: 8080

        - name: frontend
          image: gcr.io/YOUR_PROJECT/frontend:latest
          ports:
            - containerPort: 3000