apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autorootx.fullname" . }}-backend-config
  labels:
    {{- include "autorootx.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  APP_CORS_ALLOWED_ORIGINS: {{ .Values.backend.config.appCorsAllowedOrigins | quote }}
  GCP_PROJECT: {{ .Values.backend.config.gcpProject | quote }}
  GCP_REGION: {{ .Values.backend.config.gcpRegion | quote }}
  VERTEX_MODEL: {{ .Values.backend.config.vertexModel | quote }}
  SERVICENOW_MOCK: {{ .Values.backend.config.serviceNowMockMode | quote }}
  SERVICENOW_URL: {{ .Values.backend.config.serviceNowUrl | quote }}
  SERVICENOW_USER: {{ .Values.backend.config.serviceNowUser | quote }}