package com.autorootx.plugin.impl;

import com.autorootx.model.AnalysisRequest;
import com.autorootx.model.AnalysisResult;
import com.autorootx.model.Vulnerability;
import com.autorootx.plugin.Analyzer;
import com.autorootx.service.TrivyService;
import com.autorootx.service.VertexAIService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
<<<<<<< Updated upstream
=======
import org.springframework.beans.factory.annotation.Value;
>>>>>>> Stashed changes
import org.springframework.stereotype.Component;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Optional;

<<<<<<< Updated upstream
=======
/**
 * Container image vulnerability scanner.
 *
 * Prefers Trivy JSON generated by a sidecar and sends a compact,
 * structured vulnerability summary to Vertex AI for remediation guidance.
 * Falls back to the curated demo data when no Trivy report is available.
 */
>>>>>>> Stashed changes
@Component
public class ImageAnalyzer implements Analyzer {

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final int MAX_VERTEX_FINDINGS = 25;
<<<<<<< Updated upstream

    private final VertexAIService ai;
    private final TrivyService trivy;

    public ImageAnalyzer(VertexAIService ai, TrivyService trivy) {
=======
    private static final int MAX_RAW_REPORT_CHARS = 20_000;

    private final VertexAIService ai;

    @Value("${trivy.report.path:}")
    private String trivyReportPath;

    public ImageAnalyzer(VertexAIService ai) {
>>>>>>> Stashed changes
        this.ai = ai;
        this.trivy = trivy;
    }

    @Override public String id()       { return "IMAGE"; }
    @Override public String name()     { return "Image Scanner"; }
    @Override public String category() { return "SECURITY"; }
<<<<<<< Updated upstream
    @Override public List<String> inputs() { return List.of("image", "trivyReport"); }
=======
    @Override public List<String> inputs() { return List.of("image", "trivyReport", "trivyReportPath"); }
>>>>>>> Stashed changes

    @Override
    public AnalysisResult analyze(AnalysisRequest req) {
        Map<String, Object> payload = req.payload == null ? Map.of() : req.payload;
        String image = String.valueOf(payload.getOrDefault("image", "unknown:latest"));

<<<<<<< Updated upstream
        Optional<TrivyService.TrivyScanResult> payloadScan = parsePayloadTrivyReport(payload);
        TrivyService.TrivyScanResult scan = payloadScan.orElseGet(() -> trivy.scanImage(image));
        boolean trivyAvailable = scan.available();
        List<Vulnerability> vulns = trivyAvailable && !scan.vulnerabilities().isEmpty()
                ? scan.vulnerabilities()
                : detectVulnerabilities(image);

        String vulnSummary = buildVulnSummary(image, vulns, trivyAvailable ? "Trivy sidecar scan" : "Fallback static CVE dataset (Trivy unavailable)");

        AnalysisResult r = new AnalysisResult();
=======
        Optional<TrivyScan> trivyScan = loadTrivyScan(payload);
        List<Vulnerability> vulns = trivyScan
                .map(TrivyScan::vulnerabilities)
                .filter(list -> !list.isEmpty())
                .orElseGet(() -> detectDemoVulnerabilities(image));

        String vulnSummary = trivyScan
                .map(scan -> buildTrivySummary(image, scan))
                .orElseGet(() -> buildVulnSummary(image, vulns, "Demo fallback scan"));

        String aiAnalysis;
>>>>>>> Stashed changes
        try {
            VertexAIService.CallResult call = ai.analyzeWithMetrics("IMAGE", vulnSummary);
            r.summary = call.text();
            r.aiUsage = ai.toAiUsage(call);
        } catch (Exception e) {
            r.summary = "AI analysis unavailable: " + e.getMessage();
            r.aiUsage = ai.usageForException(e);
        }

        for (Vulnerability v : vulns) {
            if (v.fix == null || v.fix.isBlank()) {
                v.fix = generateFix(v);
            }
        }

        r.severity = highestSeverity(vulns);
<<<<<<< Updated upstream
        r.confidence = trivyAvailable ? "TRIVY" : "80%";
        r.rootCause = trivyAvailable
                ? "Trivy detected vulnerable packages in the scanned container image"
                : "Trivy sidecar unavailable, using fallback known-vulnerability dataset";
        r.impact = criticalCount(vulns) + " critical, " + highCount(vulns) + " high severity vulnerabilities detected";
        r.fix = trivyAvailable
                ? "Apply the Vertex AI remediation plan, upgrade fixed package versions, and rebuild the image"
                : "Upgrade base image and enable Trivy sidecar connectivity for live scan results";
=======
        r.confidence = trivyScan.isPresent() ? "TRIVY" : "85%";
        r.rootCause = trivyScan.isPresent()
                ? "Trivy detected vulnerable packages in the container image or application layers"
                : "Outdated package versions in base image with known CVEs";
        r.impact = criticalCount(vulns) + " critical, " + highCount(vulns) + " high severity vulnerabilities detected";
        r.fix = "Apply the Vertex AI remediation plan, upgrade fixed package versions, and rebuild the image";
>>>>>>> Stashed changes
        r.vulnerabilities = vulns;
        return r;
    }

<<<<<<< Updated upstream
    private Optional<TrivyService.TrivyScanResult> parsePayloadTrivyReport(Map<String, Object> payload) {
        Object raw = payload.getOrDefault("trivyReport", payload.get("trivy_report"));
        if (raw == null || String.valueOf(raw).isBlank()) {
            return Optional.empty();
        }

        try {
            JsonNode root = MAPPER.readTree(String.valueOf(raw));
            return Optional.of(new TrivyService.TrivyScanResult(true, parseTrivyVulnerabilities(root), String.valueOf(raw), "Trivy report supplied in request payload"));
        } catch (Exception e) {
            return Optional.of(new TrivyService.TrivyScanResult(true, List.of(), String.valueOf(raw), "Unable to parse supplied Trivy report: " + e.getMessage()));
        }
    }

    private List<Vulnerability> parseTrivyVulnerabilities(JsonNode root) {
        List<Vulnerability> vulnerabilities = new ArrayList<>();
        JsonNode results = root.path("Results");
        if (!results.isArray()) {
            results = root.path("results");
        }
        if (!results.isArray()) {
            return vulnerabilities;
        }

        for (JsonNode result : results) {
            JsonNode vulns = result.path("Vulnerabilities");
            if (!vulns.isArray()) {
                vulns = result.path("vulnerabilities");
            }
            if (!vulns.isArray()) {
                continue;
            }
            for (JsonNode node : vulns) {
                Vulnerability v = new Vulnerability();
                v.id = text(node, "VulnerabilityID", "UNKNOWN");
                v.title = text(node, "Title", v.id);
                v.severity = normalizeSeverity(text(node, "Severity", "LOW"));
                v.description = text(node, "Description", "");
                v.affectedPackage = text(node, "PkgName", "");
                v.currentVersion = text(node, "InstalledVersion", "");
                v.fixedVersion = text(node, "FixedVersion", "");
                v.cvss = extractCvss(node.path("CVSS"));
                v.fix = generateFix(v);
                vulnerabilities.add(v);
            }
        }

        return vulnerabilities.stream()
                .sorted(Comparator.comparingInt(v -> severityRank(v.severity)))
                .toList();
    }
=======
    private Optional<TrivyScan> loadTrivyScan(Map<String, Object> payload) {
        String report = stringValue(payload.get("trivyReport"))
                .or(() -> stringValue(payload.get("trivy_report")))
                .or(() -> readReportPath(payload))
                .orElse("");
>>>>>>> Stashed changes

        if (report.isBlank()) {
            return Optional.empty();
        }

        try {
            JsonNode root = MAPPER.readTree(report);
            return Optional.of(new TrivyScan(parseTrivyVulnerabilities(root), report));
        } catch (Exception e) {
            return Optional.of(new TrivyScan(List.of(), trimReport(report)));
        }
    }

    private Optional<String> readReportPath(Map<String, Object> payload) {
        String path = stringValue(payload.get("trivyReportPath"))
                .or(() -> stringValue(payload.get("trivy_report_path")))
                .orElse(trivyReportPath);

        if (path == null || path.isBlank()) {
            return Optional.empty();
        }

        try {
            Path reportPath = Path.of(path);
            if (!Files.isRegularFile(reportPath)) {
                return Optional.empty();
            }
            return Optional.of(Files.readString(reportPath));
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    private List<Vulnerability> parseTrivyVulnerabilities(JsonNode root) {
        List<Vulnerability> vulnerabilities = new ArrayList<>();
        JsonNode results = root.path("Results");
        if (!results.isArray()) {
            return vulnerabilities;
        }

        for (JsonNode result : results) {
            JsonNode vulns = result.path("Vulnerabilities");
            if (!vulns.isArray()) {
                continue;
            }
            for (JsonNode vulnNode : vulns) {
                Vulnerability v = new Vulnerability();
                v.id = text(vulnNode, "VulnerabilityID");
                v.title = text(vulnNode, "Title");
                if (v.title.isBlank()) {
                    v.title = v.id;
                }
                v.severity = normalizeSeverity(text(vulnNode, "Severity"));
                v.description = text(vulnNode, "Description");
                v.affectedPackage = text(vulnNode, "PkgName");
                v.currentVersion = text(vulnNode, "InstalledVersion");
                v.fixedVersion = text(vulnNode, "FixedVersion");
                v.cvss = cvss(vulnNode);
                v.fix = generateFix(v);
                vulnerabilities.add(v);
            }
        }

        return vulnerabilities.stream()
                .sorted(Comparator.comparingInt(v -> severityRank(v.severity)))
                .toList();
    }

    private String buildTrivySummary(String image, TrivyScan scan) {
        if (scan.vulnerabilities().isEmpty()) {
            return """
                    Image: %s

                    Trivy report could not be parsed into structured vulnerabilities.
                    Use the raw Trivy report below to produce remediation suggestions.

                    Raw Trivy report:
                    %s
                    """.formatted(image, trimReport(scan.rawReport()));
        }

        return buildVulnSummary(image, scan.vulnerabilities(), "Trivy sidecar scan");
    }

    private List<Vulnerability> detectDemoVulnerabilities(String image) {
        List<Vulnerability> list = new ArrayList<>();

        if (image.contains("java") || image.contains("spring") || image.contains("tomcat") || !image.contains("-")) {
            list.add(vuln("CVE-2021-44228", "Log4Shell - Remote Code Execution",
                    "CRITICAL", "9.0",
                    "Apache Log4j2 JNDI lookup feature allows remote code execution via crafted log messages.",
                    "log4j-core", "2.14.1", "2.17.1",
                    "Upgrade log4j-core to >= 2.17.1"));
        }

        list.add(vuln("CVE-2022-0778", "OpenSSL Infinite Loop DoS",
                "HIGH", "7.5",
                "BN_mod_sqrt() function in OpenSSL can enter an infinite loop when parsing crafted certificates.",
                "openssl", "1.1.1k", "1.1.1n",
                "Update OpenSSL in the base image."));

<<<<<<< Updated upstream
=======
        list.add(vuln("CVE-2023-0464", "OpenSSL Certificate Policy DoS",
                "MEDIUM", "5.9",
                "Excessive resource usage when verifying X.509 certificate chains with policy constraints.",
                "openssl", "3.0.7", "3.0.9",
                "Upgrade the base image to include OpenSSL >= 3.0.9:\n  FROM debian:bullseye-slim  # use latest\nor run:\n  RUN apt-get update && apt-get install -y openssl=3.0.9*"));

>>>>>>> Stashed changes
        list.add(vuln("CVE-2023-38545", "curl SOCKS5 Heap Buffer Overflow",
                "CRITICAL", "9.8",
                "A heap buffer overflow exists when curl is used with SOCKS5 proxy and a very long hostname.",
                "curl", "7.88.1", "8.4.0",
                "Update curl in your Dockerfile or upgrade the base image."));

<<<<<<< Updated upstream
=======
        list.add(vuln("CVE-2022-37434", "zlib Heap Buffer Overflow",
                "HIGH", "8.1",
                "A heap-based buffer over-read/write vulnerability in inflate.c in zlib via a large gzip header.",
                "zlib", "1.2.11", "1.2.13",
                "Upgrade zlib:\n  RUN apt-get update && apt-get install -y zlib1g=1.2.13-1\nOr rebuild the image from a base that includes zlib >= 1.2.13."));

        list.add(vuln("CVE-2022-25313", "Expat Stack Exhaustion",
                "MEDIUM", "6.5",
                "Stack exhaustion in libexpat before 2.4.7 via a deeply nested XML document.",
                "libexpat", "2.4.1", "2.4.7",
                "Update libexpat:\n  RUN apt-get update && apt-get install -y libexpat1=2.4.7*"));

>>>>>>> Stashed changes
        if (image.contains("node") || image.contains("js")) {
            list.add(vuln("CVE-2021-23337", "Lodash Command Injection",
                    "HIGH", "7.2",
                    "Prototype pollution via the template function in lodash < 4.17.21.",
                    "lodash", "4.17.19", "4.17.21",
                    "Upgrade lodash to >= 4.17.21."));
        }

        return list;
    }

    private Vulnerability vuln(String id, String title, String severity, String cvss,
                               String description, String pkg, String current,
                               String fixed, String fix) {
        Vulnerability v = new Vulnerability();
        v.id = id;
        v.title = title;
        v.severity = severity;
        v.cvss = cvss;
        v.description = description;
        v.affectedPackage = pkg;
        v.currentVersion = current;
        v.fixedVersion = fixed;
        v.fix = fix;
        return v;
    }

    private String buildVulnSummary(String image, List<Vulnerability> vulns, String source) {
        StringBuilder sb = new StringBuilder();
        sb.append("Image: ").append(image).append("\n\n");
        sb.append("Scan source: ").append(source).append("\n");
        sb.append("Total vulnerabilities: ").append(vulns.size()).append("\n");
        sb.append("Critical: ").append(criticalCount(vulns)).append("\n");
        sb.append("High: ").append(highCount(vulns)).append("\n\n");
        sb.append("Ask: Prioritize the highest-risk issues and provide concrete Dockerfile/package remediation steps.\n\n");
        sb.append("Detected vulnerabilities:\n");
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
        for (Vulnerability v : vulns.stream().limit(MAX_VERTEX_FINDINGS).toList()) {
            sb.append("- ").append(v.id).append(" [").append(v.severity).append("] ")
                    .append(v.title).append(" in ").append(v.affectedPackage)
                    .append(" ").append(v.currentVersion);
            if (v.fixedVersion != null && !v.fixedVersion.isBlank()) {
                sb.append(" fixed in ").append(v.fixedVersion);
            }
            if (v.cvss != null && !v.cvss.isBlank()) {
                sb.append(" CVSS ").append(v.cvss);
            }
            sb.append("\n");
            if (v.description != null && !v.description.isBlank()) {
                sb.append("  Description: ").append(v.description).append("\n");
            }
<<<<<<< Updated upstream
=======
        }
        if (vulns.size() > MAX_VERTEX_FINDINGS) {
            sb.append("\nTruncated to top ").append(MAX_VERTEX_FINDINGS)
                    .append(" findings for Vertex prompt size control.\n");
>>>>>>> Stashed changes
        }
        return sb.toString();
    }

    private String generateFix(Vulnerability v) {
        if (v.fixedVersion == null || v.fixedVersion.isBlank()) {
<<<<<<< Updated upstream
            return "No fixed version reported. Review vendor advisory and consider package removal or compensating controls.";
=======
            return "No fixed version reported by Trivy; review vendor advisory and consider package removal or compensating controls.";
>>>>>>> Stashed changes
        }
        return "Upgrade " + v.affectedPackage + " from " + v.currentVersion
                + " to " + v.fixedVersion + " or later.";
    }

    private String highestSeverity(List<Vulnerability> vulns) {
        if (vulns.stream().anyMatch(v -> "CRITICAL".equals(v.severity))) return "CRITICAL";
        if (vulns.stream().anyMatch(v -> "HIGH".equals(v.severity))) return "HIGH";
        if (vulns.stream().anyMatch(v -> "MEDIUM".equals(v.severity))) return "MEDIUM";
        return "LOW";
    }

    private long criticalCount(List<Vulnerability> vulns) {
        return vulns.stream().filter(v -> "CRITICAL".equals(v.severity)).count();
    }

    private long highCount(List<Vulnerability> vulns) {
        return vulns.stream().filter(v -> "HIGH".equals(v.severity)).count();
    }

<<<<<<< Updated upstream
    private String text(JsonNode node, String field, String fallback) {
        String value = node.path(field).asText("");
        return value.isBlank() ? fallback : value;
    }

    private String extractCvss(JsonNode cvssNode) {
        if (cvssNode == null || !cvssNode.isObject()) {
            return "";
        }
        for (JsonNode vendorNode : cvssNode) {
            if (vendorNode.has("V3Score")) {
                return vendorNode.path("V3Score").asText("");
            }
            if (vendorNode.has("V2Score")) {
                return vendorNode.path("V2Score").asText("");
=======
    private Optional<String> stringValue(Object value) {
        if (value == null) {
            return Optional.empty();
        }
        String text = String.valueOf(value);
        return text.isBlank() ? Optional.empty() : Optional.of(text);
    }

    private String text(JsonNode node, String field) {
        return node.path(field).asText("");
    }

    private String cvss(JsonNode vulnNode) {
        JsonNode cvss = vulnNode.path("CVSS");
        if (!cvss.isObject()) {
            return "";
        }

        for (JsonNode source : cvss) {
            double v3 = source.path("V3Score").asDouble(-1);
            if (v3 >= 0) {
                return String.valueOf(v3);
            }
            double v2 = source.path("V2Score").asDouble(-1);
            if (v2 >= 0) {
                return String.valueOf(v2);
>>>>>>> Stashed changes
            }
        }
        return "";
    }

    private String normalizeSeverity(String severity) {
<<<<<<< Updated upstream
        return switch (severity == null ? "" : severity.trim().toUpperCase()) {
            case "CRITICAL", "HIGH", "MEDIUM", "LOW" -> severity.trim().toUpperCase();
=======
        String normalized = severity == null ? "" : severity.trim().toUpperCase();
        return switch (normalized) {
            case "CRITICAL", "HIGH", "MEDIUM", "LOW" -> normalized;
>>>>>>> Stashed changes
            default -> "LOW";
        };
    }

    private int severityRank(String severity) {
        return switch (severity) {
            case "CRITICAL" -> 0;
            case "HIGH" -> 1;
            case "MEDIUM" -> 2;
            default -> 3;
        };
    }
<<<<<<< Updated upstream
=======

    private String trimReport(String report) {
        if (report == null || report.length() <= MAX_RAW_REPORT_CHARS) {
            return report;
        }
        return report.substring(0, MAX_RAW_REPORT_CHARS) + "\n... [truncated]";
    }

    private record TrivyScan(List<Vulnerability> vulnerabilities, String rawReport) {}
>>>>>>> Stashed changes
}
